Generating a JSON file

In [2]:
import requests

In [6]:
url = "https://raw.githubusercontent.com/Mukunza/Hospital_data/refs/heads/main/MOCK_DATA.json"

In [7]:
r = requests.get(url)

In [8]:
r.status_code

200

In [11]:
mock_data = r.json()
print(type(mock_data))

<class 'list'>

In [12]:
mock_data[:2]

[{'patient_id': 1,
  'patient_name': 'Dagny Ferneyhough',
  'patient_dob': '9/13/1949',
  'diagnosis_code': 'T285',
  'admission_date': '2021-09-22T16:46:17Z'},
 {'patient_id': 2,
  'patient_name': 'Mahalia Beartup',
  'patient_dob': '11/14/1980',
  'diagnosis_code': 'S43394',
  'admission_date': '2021-01-02T18:51:45Z'}]

In [19]:
import pandas as pd

df = pd.DataFrame(mock_data)
print(df.shape)   # shows (rows, columns)
df.head()         # shows first 5 rows as a table

(1000, 5)

,patient_id,patient_name,patient_dob,diagnosis_code,admission_date
0,1,Dagny Ferneyhough,9/13/1949,T285,2021-09-22T16:46:17Z
1,2,Mahalia Beartup,11/14/1980,S43394,2021-01-02T18:51:45Z
2,3,Jaime Gwioneth,3/22/2019,S5309,2021-07-09T11:51:14Z
3,4,Pier Reany,3/24/1959,S92231P,2021-02-05T13:16:31Z
4,5,Christiane Boyles,7/6/1923,H34823,2021-01-13T09:32:51Z

In [20]:
print(df.dtypes)

patient_id         int64
patient_name      object
patient_dob       object
diagnosis_code    object
admission_date    object
dtype: object

In [23]:
# Convert date columns to proper datetime type
df["patient_dob"] = pd.to_datetime(df["patient_dob"])
df["admission_date"] = pd.to_datetime(df["admission_date"])

print(df.dtypes)

patient_id                      int64
patient_name                   object
patient_dob            datetime64[ns]
diagnosis_code                 object
admission_date    datetime64[ns, UTC]
dtype: object

In [53]:
df.to_csv("hospital_data.csv", index=False)
print("Saved as hospital_data.csv")

Saved as hospital_data.csv

JSON FILE - DUMMY PRODUCTS

In [ ]:
import requests

In [28]:
url_products = "https://dummyjson.com/products"

In [30]:
r = requests.get(url_products)

In [31]:
r.status_code

200

In [33]:
products_data = r.json()
print(type(products_data))

<class 'dict'>

In [42]:
import pandas as pd

products_list = products_data["products"]   
df = pd.DataFrame(products_list)

print(df.shape)
df.head()

(30, 22)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [35]:
print(df.dtypes)

products    object
total        int64
skip         int64
limit        int64
dtype: object

In [36]:
df.to_csv("products_data.csv", index=False)
print("Saved as products_data.csv")

Saved as products_data.csv

In [55]:
import os
print(os.path.abspath("products_data.csv"))

C:\Users\user\products_data.csv

JSON FILE - DUMMY PRODUCTS CARTS

In [ ]:
import requests

In [37]:
url_carts = "https://dummyjson.com/carts"

In [38]:
r = requests.get(url_carts)

In [39]:
r.status_code #checking if we got the url successfully

200

In [40]:
carts_data = r.json()
print(type(carts_data))

<class 'dict'>

In [44]:
import pandas as pd

In [50]:
import pandas as pd

carts_list = carts_data["carts"]   
df = pd.DataFrame(carts_data)

print(df.shape)
df.head()

(30, 4)

                                               carts  total  skip  limit
0  {'id': 1, 'products': [{'id': 162, 'title': 'B...    208     0     30
1  {'id': 2, 'products': [{'id': 86, 'title': 'Ma...    208     0     30
2  {'id': 3, 'products': [{'id': 24, 'title': 'Fi...    208     0     30
3  {'id': 4, 'products': [{'id': 92, 'title': 'Sp...    208     0     30
4  {'id': 5, 'products': [{'id': 161, 'title': 'S...    208     0     30

CHANGING THE CARTS DATA TO THE RIGHT FORMAT

In [45]:
carts_list = carts_data["carts"] # drilling into the carts list

In [47]:
#flattening the loops through cart as they have products nested inside them
rows = []

for cart in carts_list:
    for product in cart["products"]:
        rows.append({
            "cart_id"              : cart["id"],
            "user_id"              : cart["userId"],
            "cart_total_usd"       : cart["total"],
            "cart_total_items"     : cart["totalQuantity"],
            "cart_unique_products" : cart["totalProducts"],
            "product_id"           : product.get("id"),
            "product_title"        : product.get("title"),
            "unit_price_usd"       : product.get("price"),
            "quantity_ordered"     : product.get("quantity"),
            "line_total_usd"       : product.get("total"),
            "discount_pct"         : product.get("discountPercentage"),
            "discounted_total_usd" : product.get("discountedTotal"),
        })

df = pd.DataFrame(rows)

print(df.shape)
df.head()

(114, 12)

,cart_id,user_id,cart_total_usd,cart_total_items,cart_unique_products,product_id,product_title,unit_price_usd,quantity_ordered,line_total_usd,discount_pct,discounted_total_usd
0,1,1,13037.88,12,4,162,Blue Frock,29.99,4,119.96,12.13,105.41
1,1,1,13037.88,12,4,113,Generic Motorcycle,3999.99,3,11999.97,12.10,10547.97
2,1,1,13037.88,12,4,122,iPhone 6,299.99,3,899.97,6.69,839.76
3,1,1,13037.88,12,4,138,Baseball Ball,8.99,2,17.98,1.71,17.67
4,2,2,139.93,7,2,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12

In [51]:
print(df.dtypes)

carts    object
total     int64
skip      int64
limit     int64
dtype: object

In [52]:
df.to_csv("carts_data.csv", index=False)
print("Saved as carts_data.csv")

Saved as carts_data.csv

In [54]:
import os
print(os.path.abspath("carts_data.csv"))

C:\Users\user\carts_data.csv